[app]
backend = "discord"  # Could be a list of names to fallback on.
source = "tcp.py"  # We don't have much here, just the one file.

[app.config.discord]
# Channel constants are a path string "CHANNEL_ID"
# OR a list of them: ["CHANNEL_ID", ...]
# OR a refrence to a channel: "channel://NAME"

inbound = "channel"
# outbound = inbound

token = "token"
bot = true
