[app]
backend = "discord"  # Could be a list of names to fallback on.
source = "tcp.py"  # We don't have much here, just the one file.

[config.discord]
inbound = "channel"

# When left out, `outbound` uses the same value as `inbound`
# outbound = inbound

token = "token"
bot = true
