[app]
# `backend` could be any one of or a list of:
#  - discord
#  - irc
#  - skype
#  - slack
#  - tcp
#  - twitch
#  - twitter
backend =

# `source` (string) must be a path to a file or directory
# OR a list of string to files or directories.
# the paths are relative to this configuration file.

# source =

# You can also specify rich source objects.
[[app.source]]
name = "AwesomeSource"
path = "path/to/source"

#################### DISCORD #####################

# Channel objects are a path string "CHANNEL_ID"
# OR a list of them: ["CHANNEL_ID", ...]
# OR a refrence to a channel: "channel://NAME"

[config.discord]
# `inbound` and `outbound` must be either:
#   - channel objects
#   - strings
#   - list of strings ([CHANNEL_ID, ...])

inbound = "channel"
# outbound = inbound

token = "token"
# bot = true

[[discord.channel]]
# NOTE:
#   Channel names do not correspond with
#   the channels actual name, it is only
#   used to refrence channel objects inside
#   the configuration with "channel://{name}"
name = "blah"

# The snowflake ID of the channel.
id = 1234567890

#################### IRC #########################

[config.irc]
inbound = "channel"
# outbound = inbound

[[irc.channel]]
# The network to use.
network = "network://default"

[[irc.network]]
# NOTE:
#   Network names do not hold any real value
#   they are used to refrence network objects inside
#   the configuration with "network://{name}"
name = "default"

# The domain name address
host = "irc.rizon.net"

# The port to connect to
# port = 6667

# tls = true
# tls_verify = false

#################### TCP ########################

[config.tcp]
inbound = "channel"
# outbound = inbound

[tcp.server]


#################### TWITCH #####################

[config.twitch]

[twitch.channel]

#################### SLACK ######################

[config.slack]
